
services:
  # guacd
  guacd:
    container_name: ${GUACD_CONTAINER_NAME}
    image: guacamole/guacd:${GUAC_VERSION}
    # command: guacd -b 0.0.0.0 -L debug
    command: guacd -b 0.0.0.0 -L info       # <--- [Security] Reduced logging noise
    environment:
      # - GUACD_LOG_LEVEL=debug     # <--- For Debugging
      GUACD_LOG_LEVEL: info       # <--- Protecting from attacks
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
      - ./extensions:/etc/guacamole/extensions:ro
      - ./drive:/drive:rw
      - ./record:/record:rw

  # postgres
  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres:${POSTGRES_VERSION}
    networks:
      - guacnetwork_compose
    ports:                # <--- ADD THIS SECTION
      # - "5434:5432"  
      - "127.0.0.1:${POSTGRES_EXTERNAL_PORT}:5432"       # <--- ADD THIS LINE (Host Port : Container Port)
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data:Z

  # guacamole
  guacamole:
    container_name: ${GUACAMOLE_CONTAINER_NAME}
    group_add:
      - "1000"
    depends_on:
      - guacd
      - postgres
    environment:
      # Connection to other containers using variables
      GUACD_HOSTNAME: ${GUACD_CONTAINER_NAME}
      POSTGRESQL_HOSTNAME: ${POSTGRES_CONTAINER_NAME}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      
      # General Settings
      RECORDING_SEARCH_PATH: /record
      WEBAPP_CONTEXT: ROOT
      TOMCAT_CONNECTION_TIMEOUT: 600000
      GUACAMOLE_HOME: /etc/guacamole
      # LOGBACK_LEVEL: DEBUG    # <--- For Debugging
      LOGBACK_LEVEL: INFO         # <--- Protecting from attacks
      POSTGRESQL_AUTO_CREATE_ACCOUNTS: 'true'

      # OIDC SETTINGS
      OPENID_CLIENT_ID: ${OIDC_CLIENT_ID}
      OPENID_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OPENID_ISSUER: 'https://accounts.google.com'
      OPENID_JWKS_ENDPOINT: 'https://www.googleapis.com/oauth2/v3/certs'
      OPENID_AUTHORIZATION_ENDPOINT: 'https://accounts.google.com/o/oauth2/v2/auth'
      OPENID_REDIRECT_URI: ${OIDC_REDIRECT_URI}
      OPENID_USERNAME_CLAIM_TYPE: 'name'
      OPENID_SCOPE: 'openid email profile'
      EXTENSION_PRIORITY: 'openid, database'
      
    image: guacamole/guacamole:${GUAC_VERSION}
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
      # Maps the external port from .env to internal 8080
      # - ${GUACAMOLE_EXTERNAL_PORT}:8080/tcp
      - "127.0.0.1:${GUACAMOLE_EXTERNAL_PORT}:8080/tcp"
    restart: always

networks:
  guacnetwork_compose:
    driver: bridge

